import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export const LANGUAGES = {
  en: { code: 'en', name: 'English',            flag: '🇬🇧', dir: 'ltr' },
  id: { code: 'id', name: 'Indonesia / Melayu',  flag: '🇮🇩', dir: 'ltr' },
  ja: { code: 'ja', name: '日本語',               flag: '🇯🇵', dir: 'ltr' },
  zh: { code: 'zh', name: '中文',                 flag: '🇨🇳', dir: 'ltr' },
  ru: { code: 'ru', name: 'Русский',              flag: '🇷🇺', dir: 'ltr' },
};

export const TRANSLATIONS = {
  en: {
    // Nav
    home: 'Home', shop: 'Shop', about: 'About', help: 'Help',
    login: 'Log in', signup: 'Sign up', logout: 'Log out',
    account: 'My Account', orders: 'My Orders', admin: 'Admin',
    search: 'Search products…',
    // Hero
    hero_title: 'Shop Smarter', hero_subtitle: 'with AI',
    hero_desc: 'Discover products curated just for you. Our AI learns your taste, compares prices, and finds the best deals — all in real time.',
    browse: 'Browse Products', ask_bot: 'Ask ShopBot',
    // Product
    add_to_cart: 'Add to Cart', out_of_stock: 'Out of Stock',
    adding: 'Adding…', quick_view: 'Quick view',
    only_left: 'Only {n} left', reviews: 'reviews',
    write_review: 'Write Review', post_review: 'Post Review',
    similar: 'You Might Also Like',
    // Cart
    your_cart: 'Your Cart', cart_empty: 'Your cart is empty',
    cart_empty_desc: 'Add some products and come back!',
    subtotal: 'Subtotal', shipping: 'Shipping', tax: 'Tax (11%)',
    discount: 'Discount', total: 'Total', checkout: 'Proceed to Checkout',
    continue_shopping: '← Continue Shopping', coupon: 'Coupon code',
    apply: 'Apply',
    // Checkout
    checkout_title: 'Checkout', shipping_address: 'Shipping Address',
    full_name: 'Full Name', phone: 'Phone Number', city: 'City',
    address: 'Street Address', postal_code: 'Postal Code',
    notes: 'Order Notes (optional)', place_order: 'Place Order & Pay',
    pin_location: '📍 Pin My Location on Map',
    // Account
    profile: 'Profile', password: 'Password', coupons: 'Coupons',
    wishlist: 'Wishlist', save_changes: 'Save Changes',
    // Help
    help_title: 'Help Center', help_subtitle: 'How can we help you?',
    ask_ai: 'Ask ShopBot AI', send_complaint: 'Send Complaint / Feedback',
    your_name: 'Your Name', your_email: 'Your Email',
    subject: 'Subject', message: 'Your Message',
    attachment: 'Attachment (optional)', send: 'Send Message',
    sending: 'Sending…', sent_success: 'Message sent! We\'ll reply within 24 hours.',
    // Footer
    made_by: 'Made with ❤️ in Indonesia by Yuwanandra',
    footer_desc: 'Intelligent shopping powered by AI. Discover products tailored just for you.',
    // Categories
    all_products: 'All Products', featured: 'Featured', trending: 'Trending Now',
    recommended: 'Recommended', just_for_you: 'Just for you',
    // General
    loading: 'Loading…', error: 'Something went wrong', retry: 'Retry',
    save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit',
    close: 'Close', back: 'Back', next: 'Next', confirm: 'Confirm',
    secure_payment: 'Secure Payment', fast_shipping: 'Fast Shipping',
    returns: '30-Day Returns',
  },

  id: {
    home: 'Beranda', shop: 'Belanja', about: 'Tentang', help: 'Bantuan',
    login: 'Masuk', signup: 'Daftar', logout: 'Keluar',
    account: 'Akun Saya', orders: 'Pesanan Saya', admin: 'Admin',
    search: 'Cari produk…',
    hero_title: 'Belanja Lebih Cerdas', hero_subtitle: 'dengan AI',
    hero_desc: 'Temukan produk yang dikurasi khusus untuk Anda. AI kami mempelajari selera Anda, membandingkan harga, dan menemukan penawaran terbaik — semua secara real time.',
    browse: 'Lihat Produk', ask_bot: 'Tanya ShopBot',
    add_to_cart: 'Tambah ke Keranjang', out_of_stock: 'Stok Habis',
    adding: 'Menambahkan…', quick_view: 'Lihat Cepat',
    only_left: 'Sisa {n} saja', reviews: 'ulasan',
    write_review: 'Tulis Ulasan', post_review: 'Kirim Ulasan',
    similar: 'Mungkin Kamu Suka',
    your_cart: 'Keranjang Kamu', cart_empty: 'Keranjangmu kosong',
    cart_empty_desc: 'Tambahkan produk dan kembali lagi!',
    subtotal: 'Subtotal', shipping: 'Ongkos Kirim', tax: 'Pajak (11%)',
    discount: 'Diskon', total: 'Total', checkout: 'Lanjut ke Pembayaran',
    continue_shopping: '← Lanjut Belanja', coupon: 'Kode kupon',
    apply: 'Pakai',
    checkout_title: 'Pembayaran', shipping_address: 'Alamat Pengiriman',
    full_name: 'Nama Lengkap', phone: 'Nomor Telepon', city: 'Kota',
    address: 'Alamat Jalan', postal_code: 'Kode Pos',
    notes: 'Catatan Pesanan (opsional)', place_order: 'Pesan & Bayar',
    pin_location: '📍 Tandai Lokasiku di Peta',
    profile: 'Profil', password: 'Kata Sandi', coupons: 'Kupon',
    wishlist: 'Wishlist', save_changes: 'Simpan Perubahan',
    help_title: 'Pusat Bantuan', help_subtitle: 'Ada yang bisa kami bantu?',
    ask_ai: 'Tanya ShopBot AI', send_complaint: 'Kirim Keluhan / Masukan',
    your_name: 'Nama Kamu', your_email: 'Email Kamu',
    subject: 'Subjek', message: 'Pesanmu',
    attachment: 'Lampiran (opsional)', send: 'Kirim Pesan',
    sending: 'Mengirim…', sent_success: 'Pesan terkirim! Kami akan membalas dalam 24 jam.',
    made_by: 'Dibuat dengan ❤️ di Indonesia oleh Yuwanandra',
    footer_desc: 'Belanja cerdas berbasis AI. Temukan produk yang pas buat kamu.',
    all_products: 'Semua Produk', featured: 'Unggulan', trending: 'Sedang Tren',
    recommended: 'Rekomendasi', just_for_you: 'Khusus Untukmu',
    loading: 'Memuat…', error: 'Terjadi kesalahan', retry: 'Coba Lagi',
    save: 'Simpan', cancel: 'Batal', delete: 'Hapus', edit: 'Edit',
    close: 'Tutup', back: 'Kembali', next: 'Selanjutnya', confirm: 'Konfirmasi',
    secure_payment: 'Pembayaran Aman', fast_shipping: 'Pengiriman Cepat',
    returns: 'Retur 30 Hari',
  },

  ja: {
    home: 'ホーム', shop: 'ショップ', about: '概要', help: 'ヘルプ',
    login: 'ログイン', signup: '新規登録', logout: 'ログアウト',
    account: 'マイアカウント', orders: '注文履歴', admin: '管理者',
    search: '商品を検索…',
    hero_title: 'スマートに買い物を', hero_subtitle: 'AIで',
    hero_desc: 'あなたのためにキュレーションされた商品を見つけましょう。AIがあなたの好みを学習し、価格を比較し、最良のお得情報をリアルタイムで見つけます。',
    browse: '商品を見る', ask_bot: 'ShopBotに聞く',
    add_to_cart: 'カートに追加', out_of_stock: '在庫切れ',
    adding: '追加中…', quick_view: 'クイックビュー',
    only_left: '残り{n}点', reviews: 'レビュー',
    write_review: 'レビューを書く', post_review: 'レビューを投稿',
    similar: 'おすすめ商品',
    your_cart: 'カート', cart_empty: 'カートは空です',
    cart_empty_desc: '商品を追加してください！',
    subtotal: '小計', shipping: '送料', tax: '消費税 (11%)',
    discount: '割引', total: '合計', checkout: 'チェックアウトへ',
    continue_shopping: '← 買い物を続ける', coupon: 'クーポンコード',
    apply: '適用',
    checkout_title: 'チェックアウト', shipping_address: '配送先住所',
    full_name: '氏名', phone: '電話番号', city: '市区町村',
    address: '住所', postal_code: '郵便番号',
    notes: '注文メモ（任意）', place_order: '注文して支払う',
    pin_location: '📍 地図で場所を指定',
    profile: 'プロフィール', password: 'パスワード', coupons: 'クーポン',
    wishlist: 'ウィッシュリスト', save_changes: '変更を保存',
    help_title: 'ヘルプセンター', help_subtitle: 'どのようなお手伝いができますか？',
    ask_ai: 'ShopBot AIに質問', send_complaint: '苦情・フィードバックを送る',
    your_name: 'お名前', your_email: 'メールアドレス',
    subject: '件名', message: 'メッセージ',
    attachment: '添付ファイル（任意）', send: '送信',
    sending: '送信中…', sent_success: 'メッセージを送信しました！24時間以内に返信します。',
    made_by: '❤️ インドネシアで Yuwanandra が制作',
    footer_desc: 'AIを活用したインテリジェントなショッピング体験。',
    all_products: '全商品', featured: '注目商品', trending: '人気急上昇',
    recommended: 'おすすめ', just_for_you: 'あなたへのおすすめ',
    loading: '読み込み中…', error: 'エラーが発生しました', retry: '再試行',
    save: '保存', cancel: 'キャンセル', delete: '削除', edit: '編集',
    close: '閉じる', back: '戻る', next: '次へ', confirm: '確認',
    secure_payment: '安全な支払い', fast_shipping: '迅速な配送',
    returns: '30日間返品',
  },

  zh: {
    home: '首页', shop: '商城', about: '关于', help: '帮助',
    login: '登录', signup: '注册', logout: '退出',
    account: '我的账户', orders: '我的订单', admin: '管理员',
    search: '搜索商品…',
    hero_title: '更智能地购物', hero_subtitle: '借助 AI',
    hero_desc: '发现专为您精选的商品。我们的AI学习您的品味，比较价格，实时找到最优惠的交易。',
    browse: '浏览商品', ask_bot: '问问 ShopBot',
    add_to_cart: '加入购物车', out_of_stock: '缺货',
    adding: '添加中…', quick_view: '快速查看',
    only_left: '仅剩 {n} 件', reviews: '评价',
    write_review: '写评价', post_review: '发布评价',
    similar: '您可能也喜欢',
    your_cart: '购物车', cart_empty: '购物车是空的',
    cart_empty_desc: '去添加一些商品吧！',
    subtotal: '小计', shipping: '运费', tax: '税 (11%)',
    discount: '折扣', total: '合计', checkout: '前往结账',
    continue_shopping: '← 继续购物', coupon: '优惠券代码',
    apply: '使用',
    checkout_title: '结账', shipping_address: '收货地址',
    full_name: '姓名', phone: '电话号码', city: '城市',
    address: '街道地址', postal_code: '邮政编码',
    notes: '订单备注（可选）', place_order: '下单并付款',
    pin_location: '📍 在地图上标记位置',
    profile: '个人资料', password: '密码', coupons: '优惠券',
    wishlist: '收藏夹', save_changes: '保存更改',
    help_title: '帮助中心', help_subtitle: '我们能为您做什么？',
    ask_ai: '问 ShopBot AI', send_complaint: '发送投诉/反馈',
    your_name: '您的姓名', your_email: '您的邮箱',
    subject: '主题', message: '您的消息',
    attachment: '附件（可选）', send: '发送消息',
    sending: '发送中…', sent_success: '消息已发送！我们将在24小时内回复。',
    made_by: '❤️ 由 Yuwanandra 在印度尼西亚制作',
    footer_desc: '由AI驱动的智能购物体验，为您发现完美商品。',
    all_products: '全部商品', featured: '精选', trending: '热门',
    recommended: '推荐', just_for_you: '专为您推荐',
    loading: '加载中…', error: '出错了', retry: '重试',
    save: '保存', cancel: '取消', delete: '删除', edit: '编辑',
    close: '关闭', back: '返回', next: '下一步', confirm: '确认',
    secure_payment: '安全支付', fast_shipping: '快速配送',
    returns: '30天退货',
  },

  ru: {
    home: 'Главная', shop: 'Магазин', about: 'О нас', help: 'Помощь',
    login: 'Войти', signup: 'Регистрация', logout: 'Выйти',
    account: 'Мой аккаунт', orders: 'Мои заказы', admin: 'Админ',
    search: 'Поиск товаров…',
    hero_title: 'Покупайте умнее', hero_subtitle: 'с помощью ИИ',
    hero_desc: 'Откройте для себя товары, подобранные специально для вас. Наш ИИ изучает ваши вкусы, сравнивает цены и находит лучшие предложения в реальном времени.',
    browse: 'Смотреть товары', ask_bot: 'Спросить ShopBot',
    add_to_cart: 'В корзину', out_of_stock: 'Нет в наличии',
    adding: 'Добавляем…', quick_view: 'Быстрый просмотр',
    only_left: 'Осталось {n} шт.', reviews: 'отзывов',
    write_review: 'Написать отзыв', post_review: 'Опубликовать отзыв',
    similar: 'Вам также может понравиться',
    your_cart: 'Корзина', cart_empty: 'Корзина пуста',
    cart_empty_desc: 'Добавьте товары и возвращайтесь!',
    subtotal: 'Подытог', shipping: 'Доставка', tax: 'Налог (11%)',
    discount: 'Скидка', total: 'Итого', checkout: 'Перейти к оплате',
    continue_shopping: '← Продолжить покупки', coupon: 'Код купона',
    apply: 'Применить',
    checkout_title: 'Оформление заказа', shipping_address: 'Адрес доставки',
    full_name: 'Полное имя', phone: 'Номер телефона', city: 'Город',
    address: 'Улица и дом', postal_code: 'Почтовый индекс',
    notes: 'Примечания к заказу (необязательно)', place_order: 'Заказать и оплатить',
    pin_location: '📍 Указать место на карте',
    profile: 'Профиль', password: 'Пароль', coupons: 'Купоны',
    wishlist: 'Список желаний', save_changes: 'Сохранить изменения',
    help_title: 'Центр помощи', help_subtitle: 'Чем мы можем помочь?',
    ask_ai: 'Спросить ShopBot AI', send_complaint: 'Отправить жалобу / отзыв',
    your_name: 'Ваше имя', your_email: 'Ваш email',
    subject: 'Тема', message: 'Ваше сообщение',
    attachment: 'Вложение (необязательно)', send: 'Отправить',
    sending: 'Отправка…', sent_success: 'Сообщение отправлено! Мы ответим в течение 24 часов.',
    made_by: 'Сделано с ❤️ в Индонезии автором Yuwanandra',
    footer_desc: 'Умные покупки на основе ИИ. Найдите идеальные товары для вас.',
    all_products: 'Все товары', featured: 'Избранное', trending: 'В тренде',
    recommended: 'Рекомендуем', just_for_you: 'Специально для вас',
    loading: 'Загрузка…', error: 'Что-то пошло не так', retry: 'Повторить',
    save: 'Сохранить', cancel: 'Отмена', delete: 'Удалить', edit: 'Изменить',
    close: 'Закрыть', back: 'Назад', next: 'Далее', confirm: 'Подтвердить',
    secure_payment: 'Безопасная оплата', fast_shipping: 'Быстрая доставка',
    returns: 'Возврат 30 дней',
  },
};

export const useLanguageStore = create(
  persist(
    (set, get) => ({
      language: 'en',
      setLanguage: (code) => set({ language: code }),
      // Translate a key, optionally replacing {n} placeholder
      t: (key, vars = {}) => {
        const { language } = get();
        let str = TRANSLATIONS[language]?.[key] || TRANSLATIONS['en']?.[key] || key;
        Object.entries(vars).forEach(([k, v]) => {
          str = str.replace(`{${k}}`, v);
        });
        return str;
      },
    }),
    { name: 'shopai_language' }
  )
);